name: 'Pterodactyl Backup Manager'
description: 'Creates a backup on Pterodactyl panel with automatic rotation'
author: MAXOUXAX

branding:
  icon: save
  color: blue

inputs:
  panel-url:
    required: true
    description: 'Pterodactyl panel URL'
  server-id:
    required: true
    description: 'Server ID to backup'
  api-key:
    required: true
    description: 'Pterodactyl API key'
  headers:
    required: false
    description: 'Extra headers (JSON object or "Header: Value" lines)'

outputs:
  backup-uuid:
    description: 'UUID of the created backup'

runs:
  using: node20
  main: dist/index.js
